version: '2'
services:
  php:
    build: ../php/
    volumes:
      - ./:/app
    working_dir: /app
  web:
    build: ../nginx/
    volumes:
      - ./:/app
    depends_on:
      - php
    ports:
      - 8080:80
  mysql:
    image: mysql:5.7.21
    volumes:
      - ./:/app
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    working_dir: /app
volumes:
  dbdata:
